name: Build Android Engine

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - targetos: android
            targetarch: multiarch

    env:
      SDL_VERSION: 2.32.10
      FFMPEG_VERSION: 7.1
      GH_CPU_ARCH: ${{ matrix.targetarch }}
      GH_CPU_OS: ${{ matrix.targetos }}
      GH_CROSSCOMPILING: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: bash scripts/gha/deps_android.sh

      - name: Build engine
        run: bash scripts/gha/build_android.sh

      - name: Upload engine (artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: artifact-android
          path: artifacts/*
